### ISSUE TITLE
代码还在更新吗

### ISSUE THREAD

**Issue by channingbox** [mengkunsoft/OneQRCode#2]
都2019了，QQ和微信中能不能直接调用付款了？

**Comment by mengkunsoft** [comment]
QQ和微信中无法直接调用付款是QQ、微信方面的限制引起的，不是本代码的问题

**Comment by channingbox** [comment]
我的意思是都过去两年了，微信应该会改api，竟然没有。

**Comment by huangsijun17** [comment]
> 我的意思是都过去两年了，微信应该会改api，竟然没有。

除非腾讯、阿里不想支持老款的二维码，不然不可能改接口的。
一改接口，全国千千万万的二维码全部失效。
