### ISSUE TITLE
作者觉得这个怎么样

### ISSUE THREAD

**Issue by qingyuan0o0** [mengkunsoft/OneQRCode#3]
<script type="text/javascript" src="//static.runoob.com/assets/qrcode/qrcode.min.js"></script>
<div id="qrcode"></div>
<script type="text/javascript">
var qrcode = new QRCode(document.getElementById("qrcode"));
qrcode.makeCode("https://abc.xyz");
</script>

**Comment by mengkunsoft** [comment]
很赞！现已将二维码改为前端生成
